<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-T0TIKOH" failures="1" tests="3" name="com.mailchimp.automation.testcases.SignUpPageTest" time="9.079" errors="0" timestamp="09 Aug 2018 18:52:20 GMT" skipped="0">
  <testcase classname="com.mailchimp.automation.testcases.SignUpPageTest" name="verifySignUpWithInvalidEmail" time="3.480"/>
  <testcase classname="com.mailchimp.automation.testcases.SignUpPageTest" name="verifySignUpWithExistingUser" time="3.455"/>
  <testcase classname="com.mailchimp.automation.testcases.SignUpPageTest" name="verifySignUpValidInfo" time="2.144">
    <failure message="expected [Check your email!] but found [Please check your entry and try again.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Check your email!] but found [Please check your entry and try again.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.mailchimp.automation.testcases.SignUpPageTest.verifySignUpValidInfo(SignUpPageTest.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.mailchimp.automation.suite.TestStarter.start(TestStarter.java:37)
	at com.mailchimp.automation.MailChimpApp.main(MailChimpApp.java:22)
]]>
    </failure>
  </testcase> <!-- verifySignUpValidInfo -->
</testsuite> <!-- com.mailchimp.automation.testcases.SignUpPageTest -->
